export const legalPages = {
  privacy: {
    title: "Privacy Policy",
    updatedAt: "Last updated: June 9, 2026",
    body: [
      "1. Introduction",
      "Welcome to NextTouch CRM.",
      "This Privacy Policy explains how NextTouch CRM (\"we\", \"our\", or \"us\") collects, uses, stores, and protects information when users connect their Facebook Pages, Instagram Business Accounts, and other communication channels to our platform.",
      "By using NextTouch CRM, you agree to the practices described in this Privacy Policy.",
      "2. Information We Collect",
      "When using NextTouch CRM, we may collect:",
      "User account information; name and email address; Facebook Page information authorized by the user; Instagram Business Account information authorized by the user; customer messages received through connected channels; communication history within the platform; and technical information necessary for platform operation.",
      "We collect only the information required to provide CRM services.",
      "3. How We Use Information",
      "We use collected information to provide CRM functionality, display customer conversations, enable message management and replies, improve platform performance, provide customer support, and maintain platform security.",
      "We do not sell personal information to third parties.",
      "4. Data Storage and Security",
      "We implement reasonable technical and organizational measures to protect information against unauthorized access, alteration, disclosure, or destruction.",
      "Data is stored on secure infrastructure and accessed only by authorized users and administrators.",
      "5. Third-Party Services",
      "NextTouch CRM integrates with third-party platforms, including Meta (Facebook and Instagram) and other communication and automation platforms as configured by users.",
      "Use of those services is also governed by their respective privacy policies.",
      "6. Data Retention",
      "We retain information only as long as necessary to provide services, comply with legal obligations, resolve disputes, and enforce agreements.",
      "Users may request deletion of their data as described below.",
      "7. Data Deletion Requests",
      "Users may request deletion of their account and associated data by contacting: Email: [support@yourdomain.com]",
      "We will process deletion requests within a reasonable timeframe unless retention is required by law.",
      "8. Changes to This Policy",
      "We may update this Privacy Policy periodically.",
      "Updates will be published on this page.",
      "9. Contact Information",
      "Company: [COMPANY NAME]",
      "Email: [support@yourdomain.com]",
      "Website: https://crmasd.dovi.shop"
    ]
  },
  terms: {
    title: "Terms of Service",
    updatedAt: "Last updated: June 9, 2026",
    body: [
      "1. Acceptance of Terms",
      "By accessing or using NextTouch CRM, you agree to these Terms of Service.",
      "If you do not agree, you should not use the platform.",
      "2. Description of Service",
      "NextTouch CRM is a customer communication and relationship management platform that allows businesses to manage customer conversations across connected communication channels.",
      "3. User Responsibilities",
      "Users agree to provide accurate information, maintain account security, use the platform in compliance with applicable laws, and respect Meta Platform Policies and other third-party platform requirements.",
      "Users are responsible for all activity performed through their accounts.",
      "4. Prohibited Activities",
      "Users may not use the platform for unlawful purposes, send spam or unauthorized communications, attempt to access data without authorization, or interfere with platform operation.",
      "5. Third-Party Platforms",
      "Certain features depend on third-party services such as Facebook and Instagram.",
      "Availability of those services is outside our control.",
      "6. Suspension and Termination",
      "We reserve the right to suspend or terminate accounts that violate these Terms or applicable laws.",
      "7. Limitation of Liability",
      "The service is provided on an \"as available\" basis.",
      "We are not liable for indirect, incidental, or consequential damages arising from use of the platform.",
      "8. Changes to Terms",
      "We may modify these Terms from time to time.",
      "Continued use of the platform constitutes acceptance of updated Terms.",
      "9. Contact Information",
      "Company: [COMPANY NAME]",
      "Email: [support@yourdomain.com]",
      "Website: https://crmasd.dovi.shop"
    ]
  },
  deletion: {
    title: "Data Deletion Instructions",
    updatedAt: "Last updated: June 9, 2026",
    body: [
      "If you wish to delete your data associated with NextTouch CRM, please send a request to:",
      "Email: [support@yourdomain.com]",
      "Include:",
      "Your name; email address associated with your account; and the request to delete your account and associated data.",
      "After verifying your identity, we will process your request within a reasonable period.",
      "If certain information must be retained for legal, security, or compliance reasons, only the required information will be retained.",
      "For questions regarding data deletion, contact:",
      "Email: [support@yourdomain.com]"
    ]
  }
};
